from __future__ import annotations

import math
import os
from collections import Counter
from typing import Dict

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from datasets import load_dataset
from transformers import AutoTokenizer


def round_up_multiple(x: int, base: int = 8) -> int:
    return int(math.ceil(x / base) * base)


def compute_and_save_plots(
    lengths: np.ndarray, label_counts: Dict[str, int], out_dir: str
):
    os.makedirs(out_dir, exist_ok=True)
    plt.figure(figsize=(8, 4))
    sns.histplot(lengths, bins=50, kde=False)
    plt.xlabel("Token length")
    plt.ylabel("Count")
    plt.title("Token length distribution")
    plt.tight_layout()
    p1 = os.path.join(out_dir, "text_length_distribution.png")
    plt.savefig(p1)
    plt.close()

    plt.figure(figsize=(8, 4))
    labels = list(label_counts.keys())
    counts = [label_counts[k] for k in labels]
    sns.barplot(x=labels, y=counts)
    plt.xlabel("Label")
    plt.ylabel("Count")
    plt.title("Label distribution")
    plt.tight_layout()
    p2 = os.path.join(out_dir, "label_distribution.png")
    plt.savefig(p2)
    plt.close()
    return p1, p2


def build_summary_md(stats: Dict, out_md_path: str, figures: Dict[str, str]):
    lines = [
        "# PHASE 1 — Data Summary",
        "",
        "This file was generated by running `python bert_emotion_project/scripts/phase1_data_prep.py`",
        "",
        "## Dataset",
        f"- HuggingFace dataset id: {stats['dataset_id']}",
        f"- Train samples (original): {stats['n_samples']}",
        "",
        "## Token length (BERT tokenization)",
        f"- Mean: {stats['mean_length']:.2f}",
        f"- Median: {stats['median_length']}",
        f"- Max: {stats['max_length']}",
        f"- 95th percentile (raw): {stats['p95_length']}",
        "",
        "## MAX_LENGTH decision",
        f"- Percentile used: {stats['percentile']}%",
        f"- Raw percentile value: {stats['p95_length']}",
        f"- Rounded up to nearest multiple of {stats['round_base']}: {stats['max_length_chosen']}",
        f"- Truncation ratio (proportion longer than MAX_LENGTH): {stats['truncation_ratio']:.4f}",
        "",
        "## Label distribution (train split)",
        "",
        "Label | Count | Proportion",
        "--- | --- | ---",
    ]
    for lbl, cnt in stats["label_counts"].items():
        prop = cnt / stats["n_samples"]
        lines.append(f"{lbl} | {cnt} | {prop:.4f}")

    lines += [
        "",
        "## Imbalance analysis",
        f"- Majority class count: {stats['majority_count']}",
        f"- Minority class count: {stats['minority_count']}",
        f"- Imbalance ratio (majority/minority): {stats['imbalance_ratio']:.2f}",
        "",
        "## Validation split (stratified 90/10)",
        f"- Validation fraction used: {stats['val_frac']}",
        f"- Max absolute difference in class proportions (train vs val): {stats['max_prop_diff']:.4f}",
        "",
        "## Plots",
        f"- Label distribution: {figures['label']}",
        f"- Token length distribution: {figures['length']}",
        "",
        "## Notes",
        "- Tokenization: bert-base-uncased (transformers AutoTokenizer)",
        "- Stratified split uses datasets.train_test_split with `stratify_by_column='label'`.",
    ]

    with open(out_md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def update_config_max_length(config_path: str, chosen_max_length: int):
    text = open(config_path, "r", encoding="utf-8").read()
    assign_line = f"CONFIG['tokenization']['max_length'] = {chosen_max_length}\n"
    if "CONFIG['tokenization']['max_length']" in text:
        import re

        text = re.sub(
            r"CONFIG\['tokenization'\]\['max_length'\]\s*=\s*\d+\s*\n",
            assign_line,
            text,
        )
    else:
        text = text.rstrip() + "\n\n# Updated by phase1_data_prep.py\n" + assign_line
    open(config_path, "w", encoding="utf-8").write(text)


def main():
    dataset_id = "shreyaspullehf/emotion_dataset_100k"
    percentile = 95
    round_base = 8
    val_frac = 0.1
    seed = 42
    out_md = os.path.join(
        os.path.dirname(os.path.dirname(__file__)), "docs", "PHASE_1_DATA_SUMMARY.md"
    )
    fig_dir = os.path.join(
        os.path.dirname(os.path.dirname(__file__)), "reports", "figures"
    )

    ds = load_dataset(dataset_id)
    train_split = ds["train"]
    columns = set(train_split.column_names)
    text_col = "text" if "text" in columns else "sentence"
    label_col = "label" if "label" in columns else "emotion"
    tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=True)

    lengths = []
    batch_size = 1024
    for i in range(0, len(train_split), batch_size):
        batch_texts = [str(t) for t in train_split[text_col][i : i + batch_size]]
        enc = tokenizer(batch_texts, add_special_tokens=True, truncation=False)
        for ids in enc["input_ids"]:
            lengths.append(len(ids))
    lengths = np.array(lengths)

    n_samples = len(lengths)
    mean_length = float(np.mean(lengths))
    median_length = int(np.median(lengths))
    max_length = int(np.max(lengths))
    p95_length = int(np.percentile(lengths, percentile))
    chosen = round_up_multiple(p95_length, base=round_base)
    truncation_ratio = float((lengths > chosen).sum() / n_samples)

    label_counter = Counter(train_split[label_col])
    majority = max(label_counter.values())
    minority = min(label_counter.values())
    imbalance_ratio = majority / minority if minority > 0 else float("inf")

    from datasets import ClassLabel

    label_names = sorted(list(set(train_split[label_col])))
    class_label = ClassLabel(names=label_names)
    train_split = train_split.cast_column(label_col, class_label)

    split = train_split.train_test_split(
        test_size=val_frac, stratify_by_column=label_col, seed=seed
    )
    new_train = split["train"]
    val_split = split["test"]

    t_df = pd.DataFrame(
        {text_col: new_train[text_col], label_col: new_train[label_col]}
    )
    v_df = pd.DataFrame(
        {text_col: val_split[text_col], label_col: val_split[label_col]}
    )
    full_props = t_df[label_col].value_counts(normalize=True).sort_index()
    val_props = (
        v_df[label_col].value_counts(normalize=True).reindex(full_props.index).fillna(0)
    )
    prop_diff = (full_props - val_props).abs()
    max_prop_diff = float(prop_diff.max())

    figures = {}
    fig_len, fig_lab = compute_and_save_plots(lengths, dict(label_counter), fig_dir)
    figures["length"] = fig_len
    figures["label"] = fig_lab

    stats = {
        "dataset_id": dataset_id,
        "n_samples": n_samples,
        "mean_length": mean_length,
        "median_length": median_length,
        "max_length": max_length,
        "p95_length": p95_length,
        "percentile": percentile,
        "round_base": round_base,
        "max_length_chosen": chosen,
        "truncation_ratio": truncation_ratio,
        "label_counts": dict(label_counter),
        "majority_count": majority,
        "minority_count": minority,
        "imbalance_ratio": imbalance_ratio,
        "val_frac": val_frac,
        "max_prop_diff": max_prop_diff,
    }

    config_path = os.path.join(
        os.path.dirname(os.path.dirname(__file__)), "src", "config.py"
    )
    update_config_max_length(config_path, chosen)

    build_summary_md(stats, out_md, figures)

    print(f"95th percentile (tokens): {p95_length}")
    print(f"MAX_LENGTH chosen (rounded to {round_base}): {chosen}")
    print(f"truncation_ratio: {truncation_ratio:.4f}")
    print(f"imbalance_ratio (maj/min): {imbalance_ratio:.2f}")
    print(f"PHASE 1 summary written to: {out_md}")


if __name__ == "__main__":
    main()
